trigger:
  - main

pool:
  name: Default

steps:
  - script: echo "Hello, it's my Azure DevOps App"
    displayName: 'Run an echo command'

  - script: mvn clean install
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build with Maven'

  - script: java -jar $(Build.SourcesDirectory)/target/HelloMaven-0.0.1-SNAPSHOT.jar
    displayName: 'Run the built JAR'
