trigger:
  - main

pool:
  name: Default  # Make sure this matches your self-hosted agent pool name

steps:
  - script: echo "Hello, it's my Azure DevOps App"
    displayName: 'Run an echo command'

  - script: mvn clean install
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build with Maven'

  - script: dir "$(Build.SourcesDirectory)\target"
    displayName: 'List files in target folder'

  - script: java -jar "$(Build.SourcesDirectory)\target\HelloMaven-0.0.1-SNAPSHOT.jar"
    displayName: 'Run the built JAR'
